# Generated by Django 4.0.2 on 2022-04-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lessons_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
