# Generated by Django 4.0.2 on 2022-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_lessons_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_type',
            field=models.FileField(blank=True, choices=[('resources/icons/word.ico', 'Word'), ('resources/icons/pdf.ico', 'PDF')], null=True, upload_to=''),
        ),
    ]
