# Generated by Django 4.0.2 on 2022-04-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_lessonsdescriptions_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsdescriptions',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.lessons', to_field='slug', verbose_name='Урок'),
        ),
    ]
