# Generated by Django 4.0.2 on 2022-04-19 17:54

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_lessonsdescriptions_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='topic_content',
            field=models.FileField(upload_to=main.models.PathAndRename('resources/lessons/'), verbose_name='Файл'),
        ),
    ]
