# Generated by Django 4.0.2 on 2022-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_files_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название предмета'),
        ),
    ]
