# Generated by Django 4.0.2 on 2022-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_lessons_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_type',
            field=models.FileField(blank=True, choices=[('', 'Ничего не выбрано'), ('resources/icons/word.ico', 'Word'), ('resources/icons/pdf.ico', 'PDF')], null=True, upload_to=''),
        ),
    ]
