# Generated by Django 4.0.2 on 2022-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_files_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_type',
            field=models.FileField(blank=True, choices=[('', 'Ничего не выбрано'), ('resources/icons/word.ico', 'Word'), ('resources/icons/pdf.ico', 'PDF')], null=True, upload_to='', verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(default='Неизвестный', max_length=100, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='photo',
            field=models.ImageField(upload_to='images/lessons/', verbose_name='Фотография предмета'),
        ),
    ]
