# Generated by Django 4.0.2 on 2022-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_files_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_type',
            field=models.FileField(blank=True, choices=[('', 'Ничего не выбрано'), ('resources/icons/word.ico', 'Word'), ('resources/icons/pdf.ico', 'PDF'), (' ', 'Другой формат')], null=True, upload_to='', verbose_name='Тип файла'),
        ),
    ]
