# Generated by Django 4.0.2 on 2022-04-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_lessons_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsdescriptions',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons', verbose_name='Урок'),
        ),
    ]
